### PR TITLE
Port STI calculation code

### PR DESCRIPTION
**Pull request by wbinek**

### CODE REVIEW

**Comment by nicolas-f** [comment]
Hi,
Thanks for the pull request.
Can you set the header file on nc_curve file like the other files ?
Can you add some comments on this class file, in order to explain what nc_curve do and to add a reference to the document you used to implement the STI computation ?

**Comment by wbinek** [comment]
Yes, no problem. I will add such comments. 

Basically the STI computation is based on IEC:60268-16:2011 standard. The NC curves are used to introduce background noise to the STI calculation (see: https://www.engineeringtoolbox.com/nc-noise-criterion-d_725.html).

**Comment by J51n1989** [comment]
Hi!, i am a universitary user of i-simpa and i need to do some STI calculations for a proyect. I see you work in a code, but i am not good whit python, is there a place where to learn about how to do it? (i mean, is that simply as paste this code in the source code of isimpa?) i'll apreciate your help here

**Comment by nicolas-f** [comment]
@J51n1989 Hi, you can find @wbinek version of I-Simpa here https://ci.appveyor.com/project/nicolas-f/i-simpa/builds/31870274/artifacts , please note that we still not have validated the results of this contribution.

**Comment by elyurn** [comment]
Hello!

Do you know when the calculation of the STI will be officially supported please?
Thank you very (very) much for all your work on this opensource project.

**Comment by martinritchie** [comment]
@nicolas-f , 

Sorry to bother you with some basic questions but I am not familiar with this code base: what is the status of this PR and is it ready for merging but awaiting the final approval?

**Comment by BurakAyva** [comment]
> @J51n1989 Hi, you can find @wbinek version of I-Simpa here https://ci.appveyor.com/project/nicolas-f/i-simpa/builds/31870274/artifacts , please note that we still not have validated the results of this contribution.

Hi @nicolas-f , I Githup has one month retention policy and it removed this build from Githum. Would you please upload the built with STI again?

**Pull request merged**
